$WshShell = New-Object -ComObject WScript.Shell
$DesktopPath = [Environment]::GetFolderPath("Desktop")
$ShortcutPath = Join-Path $DesktopPath "Open Al Raziq POS.lnk"

# Remove existing shortcut if any
if (Test-Path $ShortcutPath) { Remove-Item $ShortcutPath }

$Shortcut = $WshShell.CreateShortcut($ShortcutPath)
$Shortcut.TargetPath = "C:\Users\HP\Desktop\al-raziq-pos-main\Launch_App.bat"
$Shortcut.WorkingDirectory = "C:\Users\HP\Desktop\al-raziq-pos-main"
$Shortcut.Description = "Launch Al Raziq POS System"

# Use Al Raziq logo ICO (generated by scripts\make-icon.ps1)
$IconPath = "C:\Users\HP\Desktop\al-raziq-pos-main\public\favicon.ico"
$Shortcut.IconLocation = $IconPath

$Shortcut.Save()
Write-Host "SUCCESS: Shortcut created on Desktop at $ShortcutPath"
