/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUnlicensedRouteImport } from './routes/_app/unlicensed'
import { Route as AppTablesRouteImport } from './routes/_app/tables'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRoomsRouteImport } from './routes/_app/rooms'
import { Route as AppReturnsRouteImport } from './routes/_app/returns'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPromotionsRouteImport } from './routes/_app/promotions'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppKdsRouteImport } from './routes/_app/kds'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUnlicensedRoute = AppUnlicensedRouteImport.update({
  id: '/unlicensed',
  path: '/unlicensed',
  getParentRoute: () => AppRoute,
} as any)
const AppTablesRoute = AppTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppKdsRoute = AppKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/kds': typeof AppKdsRoute
  '/menu': typeof AppMenuRoute
  '/orders': typeof AppOrdersRoute
  '/pos': typeof AppPosRoute
  '/promotions': typeof AppPromotionsRoute
  '/reports': typeof AppReportsRoute
  '/returns': typeof AppReturnsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/staff': typeof AppStaffRoute
  '/tables': typeof AppTablesRoute
  '/unlicensed': typeof AppUnlicensedRoute
}
export interface FileRoutesByTo {
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/kds': typeof AppKdsRoute
  '/menu': typeof AppMenuRoute
  '/orders': typeof AppOrdersRoute
  '/pos': typeof AppPosRoute
  '/promotions': typeof AppPromotionsRoute
  '/reports': typeof AppReportsRoute
  '/returns': typeof AppReturnsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/shifts': typeof AppShiftsRoute
  '/staff': typeof AppStaffRoute
  '/tables': typeof AppTablesRoute
  '/unlicensed': typeof AppUnlicensedRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/customers': typeof AppCustomersRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/kds': typeof AppKdsRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/returns': typeof AppReturnsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/tables': typeof AppTablesRoute
  '/_app/unlicensed': typeof AppUnlicensedRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/kds'
    | '/menu'
    | '/orders'
    | '/pos'
    | '/promotions'
    | '/reports'
    | '/returns'
    | '/rooms'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/tables'
    | '/unlicensed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/customers'
    | '/expenses'
    | '/inventory'
    | '/kds'
    | '/menu'
    | '/orders'
    | '/pos'
    | '/promotions'
    | '/reports'
    | '/returns'
    | '/rooms'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/tables'
    | '/unlicensed'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/customers'
    | '/_app/expenses'
    | '/_app/inventory'
    | '/_app/kds'
    | '/_app/menu'
    | '/_app/orders'
    | '/_app/pos'
    | '/_app/promotions'
    | '/_app/reports'
    | '/_app/returns'
    | '/_app/rooms'
    | '/_app/settings'
    | '/_app/shifts'
    | '/_app/staff'
    | '/_app/tables'
    | '/_app/unlicensed'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unlicensed': {
      id: '/_app/unlicensed'
      path: '/unlicensed'
      fullPath: '/unlicensed'
      preLoaderRoute: typeof AppUnlicensedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tables': {
      id: '/_app/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AppTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns': {
      id: '/_app/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kds': {
      id: '/_app/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AppKdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppKdsRoute: typeof AppKdsRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPosRoute: typeof AppPosRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTablesRoute: typeof AppTablesRoute
  AppUnlicensedRoute: typeof AppUnlicensedRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppKdsRoute: AppKdsRoute,
  AppMenuRoute: AppMenuRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPosRoute: AppPosRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppReportsRoute: AppReportsRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTablesRoute: AppTablesRoute,
  AppUnlicensedRoute: AppUnlicensedRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
